### ISSUE TITLE
Need to differentiate between mobile bot and desktop bot

### ISSUE THREAD

**Issue by dashfwd** [varnishcache/varnish-devicedetect#18]
Right now all bots are grouped together into a single X-UA-Device of 'bot'.  But Google, for example, has bots that are specifically used for crawling mobile sites.  See:

https://developers.google.com/webmasters/smartphone-sites/googlebot-mobile
http://googlewebmastercentral.blogspot.com/2014/01/a-new-googlebot-user-agent-for-crawling.html

I'm not sure of whether there are other "mobile bot" user agents, but it might make sense to have a 'mobile-bot' X-UA-Device.

**Comment by lkarsten** [comment]
For future reference, this was added in e59973798613a5c7f5472be1c9788dd5d01cc0c1.
