### ISSUE TITLE
Microsoft Surface handling

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-devicedetect#30]
I wrote this on a comment on the commit 17c109a but it might be better to do it here:

This pattern is not correct. The second [] should be ().
The architecture is only valid on IE 10 under Windows 8 or later.

This needs to be studied a bit further but I don't think this change is correct.

**Comment by KeyserSosa** [comment]
@fgsch Good catch!  I'll patch and update the unit tests accordingly.

**Comment by KeyserSosa** [comment]
https://github.com/varnishcache/varnish-devicedetect/pull/31
