### ISSUE TITLE
new google mobile-bot

### ISSUE THREAD

**Issue by pippoppo** [varnishcache/varnish-devicedetect#32]
Hi,
according to this page:
https://support.google.com/webmasters/answer/1061943
google has a new mobile bot, maybe (as per our analysis) since April 19th

In order to catch it, I've made a little change in the vcl, this one: 

43c43
<             (req.http.User-Agent ~ "iPhone" && req.http.User-Agent ~ "\(compatible; Googlebot/2.1; \+http://www.google.com/bot.html")) {
---
>             (req.http.User-Agent ~ "(iPhone|Android)" && req.http.User-Agent ~ "\(compatible; Googlebot/2.1; \+http://www.google.com/bot.html")) {

let me know if you need a pull request

thanks,
corrado

**Comment by pippoppo** [comment]
http://searchengineland.com/google-change-smartphone-user-agent-googlebot-iphone-android-april-18th-244779

**Comment by mjacksonw** [comment]
Should this just look for "Mobile", which appeared in both and would likely continue to appear amidst future changes? https://webmasters.googleblog.com/2014/01/a-new-googlebot-user-agent-for-crawling.html

**Comment by TracKer** [comment]
Can you please merge this in, because it's breaking google bot's detection.

**Comment by behid** [comment]
I've created a PR for Google Bot new user agent and Bing Bot detection: #33

**Comment by KeyserSosa** [comment]
merged, thanks!
