### ISSUE TITLE
Wrong X-UA-Device

### ISSUE THREAD

**Issue by talyaari** [varnishcache/varnish-devicedetect#35]
Hi, we're using this VCL and we get wrong detections in several computers.
Sometimes it detects chrome on windows as smartphone and sometimes it detects android chrome as a desktop. 
Is this a known issue or something went wrong with the implementation?

**Comment by Dridi** [comment]
Hello,

Could you please share the `User-Agent` headers that were wrongly processed?

Dridi

**Comment by talyaari** [comment]
Sure, the user agent is:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

I have to say that even with this UA, sometimes it works good and sometimes not.

Thanks

**Comment by behid** [comment]
Can you reproduce this issue? I've added it to the controlset.txt file on my fork and it seems that I can't reproduce it.

**Comment by talyaari** [comment]
Thanks for your response. I already solved this issue, it was some local problem.

**Comment by leevigraham** [comment]
@talyaari What was the problem?

**Comment by fgsch** [comment]
Timed out.
