### ISSUE TITLE
Add more User-Agents

### ISSUE THREAD

**Issue by miniyarov** [varnishcache/varnish-devicedetect#36]
For more user-agents you can use following device-detect.vcl from repo:
https://github.com/miniyarov/varnish-mobiletranslate

**Comment by miniyarov** [comment]
Which is based on Awesome Mobile-Detect project https://github.com/serbanghita/Mobile-Detect

**Comment by gquintard** [comment]
Would you care proposing a pull request?

**Comment by jeremylivingston** [comment]
This does raise an interesting point for my use-case. I am working to migrate from the Mobile-Detect library to Varnish-driven detection. The code linked in https://github.com/willemk/varnish-mobiletranslate seems to generate this configuration based on this library.

Is there a reason that these two projects can't combine forces into the officially endorsed repo (varnish-devicedetect)? It seems like there's a bit of duplication of effort and it would be great to have a single source of truth.

**Comment by gquintard** [comment]
There's no blocker I think. The code here is open source and other projects are welcome to it, and if someone wish to integrate their code here, we'll gladly review any all pull requests.

**Comment by gquintard** [comment]
Actually, sorry, I spoke too soon, I'm out of my jurisdiction here and can't speak in the name of the maintainer ( @KeyserSosa ).

**Comment by KeyserSosa** [comment]
@gquintard I couldn't have put it better myself!

**Comment by fgsch** [comment]
Also https://github.com/carlosabalde/mobiledetect2vcl

**Comment by passani** [comment]
I think the WURFL Module for Varnish (commercial) also deserves a mention in the README.

https://www.scientiamobile.com/page/http-and-mobile-the-missing-header

(detailed docs: https://docs.scientiamobile.com/documentation/infuze/infuze-varnish-module-user-guide )

**Comment by lkarsten** [comment]
Hi all.

Doing some late spring cleaning, after coordinating with @KeyserSosa. 

@passani Please file a PR on the README if you want to.
@miniyarov Please file a PR with tested changes if you want them incorporated.

I don't see anything else that is actionable here, so I'll close it for now.
